package gui;

import analisesintatica.AnaliseSintatica;
import arquivo.Arquivo;
import java.awt.Color;
import java.awt.Font;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.Element;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author jean
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setTitle("Análise Léxica");
        initLineNumbers();
    }

    private void initLineNumbers() {

        linesTextArea = new JTextArea("0");
        linesTextArea.setBackground(Color.LIGHT_GRAY);        
        linesTextArea.setEditable(false);
        linesTextArea.setFont(new Font("monospaced", Font.PLAIN, 12));        

        jTextArea1.getDocument().addDocumentListener(new DocumentListener(){
            
            public String getText(){
                int caretPosition = jTextArea1.getDocument().getLength();
                Element root = jTextArea1.getDocument().getDefaultRootElement();
                String text = "0" + System.getProperty("line.separator");
                
                for (int i = 1; i < root.getElementIndex( caretPosition ) + 1; i++){
                    text += i + System.getProperty("line.separator");
                }
                
                return text;
            }
            
            @Override
            public void changedUpdate(DocumentEvent de) {
                linesTextArea.setText(getText());
            }

            @Override
            public void insertUpdate(DocumentEvent de) {
                linesTextArea.setText(getText());
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                linesTextArea.setText(getText());
            } 
        });
        
        jTextArea1.setTabSize(3);
        jTextArea1.setFont(new Font("monospaced", Font.PLAIN, 12)); 
        jScrollPane1.getViewport().add(jTextArea1);
        jScrollPane1.setRowHeaderView(linesTextArea);
        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAnaliseLexica = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableAnaliseSintatica = new javax.swing.JTable();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTableAnaliseLexica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema", "Token", "Linha", "Coluna Inicial", "Coluna Final", "Erro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableAnaliseLexica.setToolTipText("");
        jScrollPane2.setViewportView(jTableAnaliseLexica);

        jTableAnaliseSintatica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pilha de Análise Sintática", "Entrada", "ERRO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTableAnaliseSintatica);

        jMenuFile.setText("Arquivo");

        jMenuItemOpen.setText("abrir");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuItemSave.setText("salvar");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSave);

        jMenuBarPrincipal.add(jMenuFile);

        jMenu2.setText("Compilador");

        jMenuItem3.setText("Analise Sintatica");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBarPrincipal.add(jMenu2);

        jMenu1.setText("Sobre");

        jMenuItem2.setText("Especificações Linguagem ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Desenvolvedores");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBarPrincipal.add(jMenu1);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(Arquivo.readFileImage(this));
        
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        // TODO add your handling code here:
        Arquivo.writeFileImage(this,jTextArea1.getText());
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        
        JOptionPane.showMessageDialog(null,"-Identificadores devem conter no máximo dez caracteres;\n" +
            "-Tabulação é considerado uma coluna;\n" +
            "-Número real deve conter ponto \".\" e  deve conter pelo menos um digito antes do ponto,ex: \"5.23\".\n",
            "Especificações",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Desenvolvido por : \n\n\t"
                + "- Arthur Buosi de Haro, RA : 131252224 \n\t"
                + "- Jean C. Massami Yamada, RA : 161256431\n\n\t"
                + "Diciplina : Compiladores - 2016","Sobre Software",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        AnaliseSintatica analiseSintatica = new AnaliseSintatica(jTextArea1.getText());
        analiseSintatica.analiseSintatica();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public static void clearTableLexico(){        
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableAnaliseLexica.getModel();
        
        while(defaultTableModel.getRowCount() > 0)
            defaultTableModel.removeRow(0);
    }
    
    public static void insereTableLexico(String lexema,String tokenName,String linha,String colunaInit,String colunaEnd,String erro){
        String [] table = {lexema,tokenName,linha,colunaInit,colunaEnd,erro};
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableAnaliseLexica.getModel();
        defaultTableModel.addRow(table);
        
    }
    
    
    public static void clearTableSintatico(){        
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableAnaliseSintatica.getModel();
        
        while(defaultTableModel.getRowCount() > 0)
            defaultTableModel.removeRow(0);
    }
    
    public static void insereTableSintatico(Stack stack,String entrada,String erro){
        String stringStack = "";
        
        if(stack != null)
            while(!stack.empty())
                stringStack += stack.pop().toString()+ " ";
        
        String [] table = {stringStack,entrada,erro};
        DefaultTableModel defaultTableModel = (DefaultTableModel) jTableAnaliseSintatica.getModel();
        defaultTableModel.addRow(table);
        
    }
    
    private JTextArea linesTextArea;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTable jTableAnaliseLexica;
    public static javax.swing.JTable jTableAnaliseSintatica;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}